### ISSUE TITLE
Error - config error 'docs dir'

### ISSUE THREAD

**Issue by dcaddick** [Tiryoh/actions-mkdocs#135]
Apologies for a dumb Q, but I'm trying to start with a basic config and come up with this error?

I can only guess that I'm doing something pretty dumb?

![image](https://user-images.githubusercontent.com/19640455/214288713-38216518-a443-408a-b457-70af1c53bec8.jpeg)

**Comment by Tiryoh** [comment]
It seems your `mkdocs.yml` is something wrong. How about checking if the build passes on your laptop?
https://www.mkdocs.org/user-guide/configuration/#docs_dir

**Comment by Tiryoh** [comment]
Feel free to reopen this issue if you still have a issue with this actions.
